const LIGHT_THEME_BACKGROUND = " bg-[#E5E5E5]";
const DARK_THEME_BACKGROUND = " dark:bg-neutral-500";

const LIGHT_THEME_FOOTER_BACKGROUND = " bg-neutral-400";
const DARK_THEME_FOOTER_BACKGROUND = " dark:bg-neutral-700";

const LIGHT_THEME_TEXT_COLOR =" text-black"
const DARK_THEME_TEXT_COLOR =" dark:text-neutral-300"

// Exports

export const BACKGROUND = LIGHT_THEME_BACKGROUND+DARK_THEME_BACKGROUND;
export const FOOTER_BACKGROUND = LIGHT_THEME_FOOTER_BACKGROUND+DARK_THEME_FOOTER_BACKGROUND
export const TEXT_COLOR = LIGHT_THEME_TEXT_COLOR+DARK_THEME_TEXT_COLOR;
