import type { Metadata } from "next";
import { aperçuFont } from "@/utils/functions/localfontloader";
import { ThemeContextProvider } from "@/contexts/theme-context";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${aperçuFont.variable}`}>
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
