import type { Metadata } from "next";
import { interTightFont, aperçuFont, basisFont } from "@/utils/localfontloader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${interTightFont.variable} ${aperçuFont.variable} ${basisFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
